Fix a possible NPE followed by a NCDFE when system property is missing
A missing system property will cause a NullPointerException and, since
it occurs in a static initializer block, cause a
NoClassDefFoundError if the 'kura.configuration' property is not set.

Signed-off-by: Jens Reimann <jreimann@redhat.com>